name: Deploy
on: [push]
jobs:
  my-job:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy demo to blog
      run: |
        cd /home/jason/www/html/public
        dir_name="/home/jason/www/html/public/ocr_bye"
        if [ ! -d "$dir_name" ]; then
          git clone https://github.com/Leisurelybear/ocr-bye.git
          echo "Clone successfully."
        else
          echo "Folder $dir_name already exists, ready to pull."
          cd $dir_name
          git pull
          echo "Update successfully."
        fi
        
