name: Deploy
on: [push]
env: 
  CODE_HOME: "/home/jason/www/html/public/ocr-bye"
jobs:
  my-job:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy demo to blog
      run: |
        if [ -d "$CODE_HOME" ]; then
          cd "$CODE_HOME"
          git pull
          echo "Code updated in $CODE_HOME."
        else
          git clone https://github.com/Leisurelybear/ocr-bye.git "$CODE_HOME"
          echo "Code cloned to $CODE_HOME."
        fi
        
